In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [80]:
df=pd.read_csv('/content/heart.csv')

In [81]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [82]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [83]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [84]:
df.dtypes

Age                 int64
Sex                object
ChestPainType      object
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int64
dtype: object

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [86]:
print(df.nunique())

Age                50
Sex                 2
ChestPainType       4
RestingBP          67
Cholesterol       222
FastingBS           2
RestingECG          3
MaxHR             119
ExerciseAngina      2
Oldpeak            53
ST_Slope            3
HeartDisease        2
dtype: int64

In [87]:
df['Cholesterol']=df['Cholesterol'].replace(0,np.nan)
df['RestingBP']=df['RestingBP'].replace(0,np.nan)

In [88]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140.0,289.0,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160.0,180.0,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130.0,283.0,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138.0,214.0,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150.0,195.0,0,Normal,122,N,0.0,Up,0

In [89]:
df['RestingBP']=df['RestingBP'].fillna(df['RestingBP'].median())
df['Cholesterol']=df['Cholesterol'].fillna(df['Cholesterol'].median())

In [90]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [91]:
columns_label_encode=['Sex','FastingBS', 'HeartDisease', 'ExerciseAngina']
for columns in columns_label_encode:
  df[columns]=le.fit_transform(df[columns])

In [92]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,ATA,140.0,289.0,0,Normal,172,0,0.0,Up,0
1,49,0,NAP,160.0,180.0,0,Normal,156,0,1.0,Flat,1
2,37,1,ATA,130.0,283.0,0,ST,98,0,0.0,Up,0
3,48,0,ASY,138.0,214.0,0,Normal,108,1,1.5,Flat,1
4,54,1,NAP,150.0,195.0,0,Normal,122,0,0.0,Up,0

In [93]:
df_final=pd.get_dummies(df,columns=['ChestPainType', 'RestingECG', 'ST_Slope'],drop_first=True)

In [94]:
df_final.shape

(918, 16)

In [95]:
df_final.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ST_Slope_Flat,ST_Slope_Up
0,40,1,140.0,289.0,0,172,0,0.0,0,True,False,False,True,False,False,True
1,49,0,160.0,180.0,0,156,0,1.0,1,False,True,False,True,False,True,False
2,37,1,130.0,283.0,0,98,0,0.0,0,True,False,False,False,True,False,True
3,48,0,138.0,214.0,0,108,1,1.5,1,False,False,False,True,False,True,False
4,54,1,150.0,195.0,0,122,0,0.0,0,False,True,False,True,False,False,True

In [96]:
columns_tobe_encoded=['ChestPainType_ATA','ChestPainType_NAP','ChestPainType_TA','RestingECG_Normal','RestingECG_ST','ST_Slope_Flat','ST_Slope_Up']
for columns in columns_tobe_encoded:
  df_final[columns]=le.fit_transform(df_final[columns])

In [97]:
df_final.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ST_Slope_Flat,ST_Slope_Up
0,40,1,140.0,289.0,0,172,0,0.0,0,1,0,0,1,0,0,1
1,49,0,160.0,180.0,0,156,0,1.0,1,0,1,0,1,0,1,0
2,37,1,130.0,283.0,0,98,0,0.0,0,1,0,0,0,1,0,1
3,48,0,138.0,214.0,0,108,1,1.5,1,0,0,0,1,0,1,0
4,54,1,150.0,195.0,0,122,0,0.0,0,0,1,0,1,0,0,1

In [98]:
num_cols = ['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak']
from sklearn.preprocessing import StandardScaler
# Initialize a fresh scaler
scaler = StandardScaler()

# Fit and Transform all 5 at once
df_final[num_cols] = scaler.fit_transform(df_final[num_cols])

In [99]:
df_final.head()

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ST_Slope_Flat,ST_Slope_Up
0,-1.433140,1,0.415002,0.858035,0,1.382928,0,-0.832432,0,1,0,0,1,0,0,1
1,-0.478484,0,1.527329,-1.184227,0,0.754157,0,0.105664,1,0,1,0,1,0,1,0
2,-1.751359,1,-0.141161,0.745617,0,-1.525138,0,-0.832432,0,1,0,0,0,1,0,1
3,-0.584556,0,0.303769,-0.547191,0,-1.132156,1,0.574711,1,0,0,0,1,0,1,0
4,0.051881,1,0.971166,-0.903182,0,-0.581981,0,-0.832432,0,0,1,0,1,0,0,1

In [100]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report

In [101]:
from sklearn.model_selection import train_test_split
X=df_final.drop('HeartDisease',axis=1)
y=df_final['HeartDisease']

In [102]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [103]:
logistic_reg=LogisticRegression()
logistic_reg.fit(X_train,y_train)

LogisticRegression()

In [104]:
y_pred_logistic=logistic_reg.predict(X_test)

In [105]:
class_report=classification_report(y_test,y_pred_logistic)
print(class_report)

              precision    recall  f1-score   support

           0       0.80      0.88      0.84        77
           1       0.91      0.84      0.87       107

    accuracy                           0.86       184
   macro avg       0.85      0.86      0.86       184
weighted avg       0.86      0.86      0.86       184

In [106]:
svm_model=SVC(kernel='rbf')
svm_model.fit(X_train,y_train)

SVC()

In [107]:
y_pred_svm=svm_model.predict(X_test)
class_report=classification_report(y_test,y_pred_svm)
print(class_report)

              precision    recall  f1-score   support

           0       0.80      0.82      0.81        77
           1       0.87      0.85      0.86       107

    accuracy                           0.84       184
   macro avg       0.83      0.83      0.83       184
weighted avg       0.84      0.84      0.84       184

In [108]:
knn_model=KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train,y_train)
y_pred_knn=knn_model.predict(X_test)
class_report=classification_report(y_test,y_pred_knn)
print(class_report)

              precision    recall  f1-score   support

           0       0.81      0.83      0.82        77
           1       0.88      0.86      0.87       107

    accuracy                           0.85       184
   macro avg       0.84      0.85      0.84       184
weighted avg       0.85      0.85      0.85       184

In [109]:
naive_model=GaussianNB()
naive_model.fit(X_train,y_train)
y_pred_naive=naive_model.predict(X_test)
class_report=classification_report(y_test,y_pred_naive)
print(class_report)

              precision    recall  f1-score   support

           0       0.78      0.90      0.83        77
           1       0.92      0.81      0.86       107

    accuracy                           0.85       184
   macro avg       0.85      0.85      0.85       184
weighted avg       0.86      0.85      0.85       184

In [110]:
model_tree_classifier=DecisionTreeClassifier()
model_tree_classifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [111]:
y_pred_tree=model_tree_classifier.predict(X_test)
class_report=classification_report(y_test,y_pred_tree)
print(class_report)

              precision    recall  f1-score   support

           0       0.76      0.82      0.79        77
           1       0.86      0.81      0.84       107

    accuracy                           0.82       184
   macro avg       0.81      0.82      0.81       184
weighted avg       0.82      0.82      0.82       184

In [112]:
import joblib

In [113]:
joblib.dump(knn_model,'KNN_MODEL.pkl')
joblib.dump(scaler,'Standadar_sclaer.pkl')
joblib.dump(X.columns.tolist(),'columns.pkl')

['columns.pkl']

In [114]:
joblib.dump(scaler, 'Standadar_sclaer.pkl')

['Standadar_sclaer.pkl']